name: Vehicles
author: JaxkDev
version: 0.2.0
api: 4.0.0
mcpe-protocol: [407]
main: JaxkDev\Vehicles\Main
website: "https://github.com/JaxkDev/Vehicles"
description: "[W.I.P] PocketMine-MP plugin that brings vehicles to your server !"

commands:
  vehicles:
    description: "Vehicles general command"
    permission: vehicles.command.use
    usage: /vehicles help
    permission-message: "[Vehicles] > You do not have permission to use vehicle commands."

permissions:
  vehicles:
    default: false
    description: "Allows user all vehicles plugin perms."
  vehicles.command:
    description: "Allows user to use all vehicle commands."
    default: false
  vehicles.command.use:
    description: "Allows user to use vehicle commands."
    default: true
  vehicles.command.spawn:
    description: "Allows user to spawn a vehicle."
    default: op
  vehicles.command.remove:
    description: "Allows user to remove a vehicle."
    default: op
  vehicles.drive:
    description: "Allows user to drive a vehicle."
    default: true
  vehicles.passenger:
    description: "Allows user to be a passenger."
    default: true
