name: Vehicles
author: JaxkDev
version: 0.1.11
api: [3.11.0]
mcpe-protocol: [440]
main: JaxkDev\Vehicles\Main
website: "https://github.com/JaxkDev/Vehicles"
description: "[W.I.P] PocketMine-MP plugin that brings vehicles to your server !"

commands:
  vehicles:
    description: "Vehicles general command"
    permission: vehicles.command.use
    usage: /vehicles help
    permission-message: "[Vehicles] > You do not have permission to use vehicle commands."

permissions:
  vehicles:
    default: false
    description: "Allows user all vehicles plugin perms."
    children:

      vehicles.command:
        description: "Allows user to use all vehicle commands."
        default: false
        children:

          vehicles.command.use:
            description: "Allows user to use vehicle commands."
            default: true
          vehicles.command.spawn:
            description: "Allows user to spawn a vehicle."
            default: op
          vehicles.command.remove:
            description: "Allows user to remove a vehicle."
            default: op

      vehicles.drive:
        description: "Allows user to drive a vehicle."
        default: true
      vehicles.passenger:
        description: "Allows user to be a passenger."
        default: true
